const menu = [
  {
    id: 1,
    title: 'Butter chicken',
    category: 'Punjab',
    price: 15.99,
    img: 'https://www.holidify.com/blog/wp-content/uploads/2015/11/316269329_c4098aa64f_o.jpg',
    desc: "While chicken may very well be called the national bird of Punjab, butter chicken is the crowning jewel of the food of Punjab. ",
  },
  {
    id: 2,
    title: ' Shakkar Para',
    category: 'Punjab',
    price: 13.99,
    img: 'https://www.holidify.com/blog/wp-content/uploads/2015/11/8163600222_794fd5164a_o.jpg',
    desc: "A great accompaniment to tea, it can also be snacked on when you're craving something a little sweet. ",
  },
  {
    id: 3,
    title: 'Chole Bature',
    category: 'Punjab',
    price: 6.99,
    img: 'https://www.holidify.com/blog/wp-content/uploads/2015/11/3376550208_e35d82e8f5_o.jpg',
    desc: "Made with flour and milk rather than wheat flour, it's different from a poori.",
  },
  {
    id: 4,
    title: 'Tunday Kebab',
    category: 'Uttar Pradesh',
    price: 20.99,
    img: 'https://www.holidify.com/blog/wp-content/uploads/2015/06/8716416557_7820fcf22d_b.jpg',
    desc: "The tender Tunday kebabs of Lucknow are famous for their savoury and melt in your mouth flavour",
  },
  {
    id: 5,
    title: 'Lucknowi Biryani',
    category: 'Uttar Pradesh',
    price: 22.99,
    img: 'https://www.holidify.com/images/cmsuploads/compressed/Lucknowi27s_Famous_Dum_Biryani_20200113161037.jpg',
    desc: "A nation-wide favourite, Lucknawi Biryani is prepared with cashew nut paste, saffron, curd, mace powder and star anise.",
  },
  {
    id: 6,
    title: 'Kulfi Falooda',
    category: 'Uttar Pradesh',
    price: 18.99,
    img: 'https://www.holidify.com/images/cmsuploads/compressed/Kulfi_Faluda_20200113162024.jpg',
    desc: "Kulfi Faloodas are prepared by adding vermicelli noodles, passion fruit seeds, rose syrup and dry fruits to ice cream or kulfi.",
  },
  {
    id: 7,
    title: 'Litti Chokha',
    category: 'Jharkhand',
    price: 8.99,
    img: 'https://www.holidify.com/blog/wp-content/uploads/2016/07/litti.jpg',
    desc: "Litti is a very famous food item in the State and savoured by the locals. It is eaten with Yoghurt, Baigan Bharta (Chokha), Alu Bharta or Papad.",
  },
  {
    id: 8,
    title: ' Rugra',
    category: 'Jharkhand',
    price: 12.99,
    img: 'https://www.holidify.com/blog/wp-content/uploads/2016/07/rugra.jpg',
    desc: "Rugra is an item which tastes like mushroom and is very delicious to eat. Rugra is basically an indigenous variety of vegetable, rich in protein and minerals and high on calorific value.",
  },
  {
    id: 9,
    title: 'Malpua',
    category: 'Jharkhand',
    price: 16.99,
    img: 'https://www.holidify.com/blog/wp-content/uploads/2016/07/malpua.jpg',
    desc: "The desi pancake or the Malpua is synonymous with Holi in Jharkhand. There is not a single household in Jharkhand where the sweet smell of malpua fills the air on the eve of Holi.",
  },
];
export default menu;
